baseURL = 'http://goodboylqs.github.io/'
languageCode = 'zh-cn'
title = '庙街'
author = 'lqs'
theme = 'hugo-theme-diary'

[taxonomies]
   category = "categories"
   tag = "tags"

[[menu.main]]
url = "/categories/读书笔记"
name = "读书笔记"
weight = 2
[[menu.main]]
url = "/categories/编程"
name = "编程"
weight = 3
[[menu.main]]
url = "/categories/会计"
name = "会计"
weight = 4



[[menu.main]]
url = "/tags"
name = "按标签搜索"
weight = 4


