name: Build and Deploy with Hugo

on:
  push:
    branches:
      - main  # 触发部署的分支（例如 main 或 master）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 如果使用 Hugo 主题作为子模块，需要启用

      # 2. 安装 Hugo（指定版本）
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # 指定 Hugo 版本
          extended: true           # 如果使用 Hugo 扩展版（例如某些主题需要）

      # 3. 构建静态网站
      - name: Build with Hugo
        run: |
          hugo --minify

      # 4. 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # 产物名称，必须与部署步骤一致
          path: ./public      # Hugo 生成的静态文件目录

      # 5. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
          publish_dir: ./public
        environment:
          name: github-pages

