name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: 
          hugo --minify --baseURL "${{ steps.deployment.outputs.page_url }}/"
          touch public/.nojekyll  # 禁用GitHub的Jekyll构建

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./public

      - name: Deploy
        uses: actions/deploy-pages@v4
        id: deployment
